# Generated by Django 5.0.4 on 2024-07-17 10:14

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
                ('age', models.PositiveIntegerField(default=0)),
                ('is_doctor', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('prediction_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sex', models.IntegerField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('BMI', models.FloatField(blank=True, default=None, null=True)),
                ('doctor_feedback', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currentSmoker', models.IntegerField(blank=True, default=None, null=True)),
                ('cigsPerDay', models.IntegerField(blank=True, default=None, null=True)),
                ('BPMeds', models.IntegerField(blank=True, default=None, null=True)),
                ('prevalentStroke', models.IntegerField(blank=True, default=None, null=True)),
                ('prevalentHyp', models.IntegerField(blank=True, default=None, null=True)),
                ('diabetes', models.IntegerField(blank=True, default=None, null=True)),
                ('totChol', models.IntegerField(blank=True, default=None, null=True)),
                ('sysBP', models.IntegerField(blank=True, default=None, null=True)),
                ('diaBP', models.IntegerField(blank=True, default=None, null=True)),
                ('heartRate', models.IntegerField(blank=True, default=None, null=True)),
                ('glucose', models.IntegerField(blank=True, default=None, null=True)),
                ('TenYearCHD', models.IntegerField(blank=True, default=None, null=True)),
                ('Urea', models.FloatField(blank=True, default=None, null=True)),
                ('Cr', models.FloatField(blank=True, default=None, null=True)),
                ('HbA1c', models.FloatField(blank=True, default=None, null=True)),
                ('Chol', models.FloatField(blank=True, default=None, null=True)),
                ('TG', models.FloatField(blank=True, default=None, null=True)),
                ('HDL', models.FloatField(blank=True, default=None, null=True)),
                ('LDL', models.FloatField(blank=True, default=None, null=True)),
                ('VLDL', models.FloatField(blank=True, default=None, null=True)),
                ('Pregnancies', models.IntegerField(blank=True, default=None, null=True)),
                ('BloodPressure', models.IntegerField(blank=True, default=None, null=True)),
                ('SkinThickness', models.IntegerField(blank=True, default=None, null=True)),
                ('Insulin', models.IntegerField(blank=True, default=None, null=True)),
                ('DiabetesPedigreeFunction', models.FloatField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
