# Generated by Django 5.0.4 on 2024-05-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0002_patienthistory_doctorfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_disease.patienthistory')),
            ],
        ),
    ]
