# Generated by Django 5.0.4 on 2024-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0003_doctorfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorfeedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='doctorfeedback',
            name='doctorFeedback',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
