# Generated by Django 5.0.4 on 2024-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0004_alter_customuser_address_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='TenYearCHD',
        ),
    ]
