# Generated by Django 5.0.4 on 2024-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0005_remove_patienthistory_tenyearchd'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='Preidction',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
