# Generated by Django 5.0.4 on 2024-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0005_remove_patienthistory_doctorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='doctor_feedback',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='DoctorFeedback',
        ),
    ]
