# Generated by Django 5.0.4 on 2024-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0006_patienthistory_doctor_feedback_delete_doctorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='patientName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
