# Generated by Django 5.0.4 on 2024-05-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_disease', '0007_patienthistory_patientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
